### PR TITLE
Update build process to generate version & release labels from git info

### PR DESCRIPTION
**Pull request by deoren**
As noted in the commit log, the intention here was to essentially extend the existing build script that it can be used as a big, "smash this button to build everything" script. You run it and then test the results, ship the files, etc.

@rgerhards I had something similar to this for my own use, but figured it might be useful for others. Thoughts?

closes rsyslog/rsyslog-doc#424

### CODE REVIEW

**Comment by deoren** [comment]
Looks like one of the options I used isn't compatible with some older versions of Git. I'll find a workaround and push that soon.

**Comment by deoren** [comment]
7a682f5ce334f83393115bd0835dd2f1bb5610a4 appears to work equally well on Ubuntu 14.04 (git 1.9.1) or on Ubuntu 16.04 (git 2.7.4). I suppose that is what I get for testing on a newer box and calling it "good enough".

**Comment by deoren** [comment]
I think I'm through with this one for a time, other than fixing anything you see as glaringly wrong. Any further tweaks can be done as a separate PR.

**Comment by rgerhards** [comment]
I need to finally look up which script builds the rsyslog.com doc and adapt it accordingly :-)

**Comment by deoren** [comment]
Looks like my attempt to rebase off of master ended up creating a weird merge situation. Going to try and fix and will note once that is done.

**Comment by deoren** [comment]
> @rgerhards: I need to finally look up which script builds the rsyslog.com doc and adapt it accordingly :-)

Cool. :)

**Comment by deoren** [comment]
@rgerhards I thought I needed to rebase due to the recent changes to `source/conf.py`, but evidently not. I reset my branch back to the commit proffered by this PR and it looks like that cleared things up: now only the relevant changes are showing for merge.

**Pull request merged**
