### PR TITLE
mention docker containers as an option for installing rsyslog

### PR DESCRIPTION
**Pull request by rgerhards**

### CODE REVIEW

**Comment by rgerhards** [comment]
@deoren this will fail -- do you have an idea if what I try to use (a common info text) is possible. And if so, how?

**Comment by deoren** [comment]
@rgerhards I should be able to look at this closer in a few hours. A workaround that comes to mind (if we cannot get substitution reference to work) would be to use an include file for the common text.

**Comment by deoren** [comment]
Doc references:

- http://docutils.sourceforge.net/docs/ref/rst/directives.html#replace

- http://docutils.sourceforge.net/docs/ref/rst/restructuredtext.html#substitution-definitions

It may be possible to escape the newlines ...

Stil, a standard include may work out better depending on how tests go.

**Comment by deoren** [comment]
At this point if it is possible, I'm not easily seeing it. For now I would create the include file and then pull it in via the `include` directive:

```
.. include:: /path/to/file.inc.rst
```

I've created a separate branch and will ref this PR in the commit log entries to link them here. If you're comfortable (or if you prefer) to have me directly make changes to branches that you provide as PRs I'm fine with making them there (as time permits) if it makes it easier for you. I'm also fine with creating branches in my repo for review.

**Comment by deoren** [comment]
Fresh build wrapping up:

http://rsyslog.whyaskwhy.org/rgerhards-install/

**Comment by rgerhards** [comment]
Thx, I agree that the include is the best solution - I hadn't seen that 👍

On the build: thx for the offer, but I build locally and use the browser directly on the file system, so except for the site theme I think I can see everything - or do I overlooking something?

**Comment by deoren** [comment]
> @rgerhards: On the build: thx for the offer, but I build locally and use the browser directly on the file system, so except for the site theme I think I can see everything - or do I overlooking something?

I was referring to committing changes to your branch directly vs creating a branch based off of yours and making changes there for demo purposes.

**Comment by rgerhards** [comment]
@deoren In my personal opinion, a commit like https://github.com/deoren/rsyslog-doc/commit/9ceb7a68aac1644c61173ea84757786e2f75784f should probably better get as it's own PR -- it is useful regardless of mine. You can then tell me to rebase after merge (which I usually do anyhow).

I have now changed mine to using include. I guess I'll create the includes container, which should not conflict with your change when submitted as PR. As a side-note, we really need to work a bit more on the install doc, and probably to doc at all. The more I do broader changes, the more I understand this is really, really needed ;-)

**Comment by deoren** [comment]
> @rgerhards: @deoren In my personal opinion, a commit like deoren/rsyslog-doc@9ceb7a6 should probably better get as it's own PR

Are you saying that file renames should get their own PRs or all of my changes up to that point? Just making sure I'm following you.

I originally created my branch for demo purposes, and I'm pretty sure I based it directly off of your branch instead of master which I understand is best practice. I wasn't thinking at the time that I would do enough work to make it useful to merge. Funny how that works.

Even so, I got curious just now and attempted to setup a PR (but not submit) against your branch. I didn't know that was supported (I thought just the parent repo could be targeted).

Is it a normal pattern for me to rebase off of your branch, submit a PR against your branch and then we merge this PR?

My branch -> Your branch -> master

If not, I suppose I could rebase off of master, submit a PR, you rebase and then merge. Extra rebase involved, but not the end of the world. Or, when you're ready you merge this PR and I then rebase off of master and submit a PR. Maybe a cleaner history that way, though I am just assuming that is how it would look (still getting used to Git).

> @rgerhards: I have now changed mine to using include. I guess I'll create the includes container, which should not conflict with your change when submitted as PR. 

See above notes. I'm glad you like the includes container. Going that route should help with deduping raw content (just one place to maintain it), but will allow placing it in multiple places (as the docs have a natural tendency to have multiple entry points via Google, direct linking, etc).

> @rgerhards: As a side-note, we really need to work a bit more on the install doc, and probably to doc at all. The more I do broader changes, the more I understand this is really, really needed ;-)

Hah, we need to work on a lot of stuff I'm afraid. :) I agree that broad changes are needed, but with the time I have to invest I currently plan to go after targeted items as medium-effort tasks, minor cleanup items as quick tasks when I have a small window of time and will mentally "cook" on larger ideas that I touch on as I work on tasks like PR #476.

I think the idea of using projects to group related issues will probably be helpful as we whiteboard larger changes so that we can break them out into smaller tasks for processing.

One example is updating the docs to use substitution references in place of literal config format names. It's something I plan to keep circling back to, but I've been distracted with other items. Ironically if it's not my day job, the last week or so it's my efforts at learning Docker. 

I blame you for that last bit. ;) I've fallen down a rabbit hole as I keep chasing the potential uses for containers: everything from building "whack-a-button" containers in order to package specific "effects" to long-term tools. I'm hooked. I'm trying to make myself go through the books/videos and other resources I have access to, but it's far more interesting to just tinker and figure it out by trying out ideas. I'm making it though.

Anyway, I'm off on a tangent at this point. If you would, let me know how you'd like to handle our two branches (who merges what) and I'll do whatever works best for you. Tomorrow is going to be really busy for me, but I will plan to carve out some time late in the day to work on this.

**Comment by deoren** [comment]
@rgerhards This looks ready to merge. Any further work needed before we do so? 

I can rebase on my end and apply any changes as a new PR. I got sidetracked from doing so last week with the discussion of whether a should create a separate PR for discussing changes to your branch or just committing directly to your branch.

It sounds like the way forward is a separate PR when I wish to compare against a PR of yours where I'd like to suggest changes.

**Comment by rgerhards** [comment]
I checked the commit, I think it is fine. Rebase is not required, as it merges. So I will do so now.

**Comment by deoren** [comment]
@rgerhards regarding a rebase, I meant on my end against master (after this merge) so I could provide my changes against your branch. Nothing big, just a few small tweaks.

**Comment by rgerhards** [comment]
args... we should untangle these issue. I always get confused with that. sorry...

**Comment by deoren** [comment]
@rgerhards not a problem, you are juggling more balls at a time than I am. ;)

**Pull request merged**
