### PR TITLE
imgssapi: rewrite documentation

### PR DESCRIPTION
**Pull request by PascalWithopf**
Module documentation was rewritten in the new style.

### CODE REVIEW

**Comment by deoren** [comment]
@PascalWithopf 

I found this note in the doc:

> Parameter are only available in Legacy Format.

Do you know if that is still true? Use of the new style seems to suggest that using the [`advanced`](http://www.rsyslog.com/doc/v8-stable/configuration/conf_formats.html) configuration format is supported.

**Comment by deoren** [comment]
I found some issues with the recent changes to imrelp.rst, impstats.rst and imptcp.rst:

```
/home/deoren/dev/rsyslog/rsyslog-doc/source/configuration/modules/impstats.rst:291: WARNING: duplicate label statistic-counter, other instance in /home/deoren/dev/rsyslog/rsyslog-doc/source/configuration/modules/imrelp.rst
/home/deoren/dev/rsyslog/rsyslog-doc/source/configuration/modules/imptcp.rst:540: WARNING: duplicate label statistic-counter, other instance in /home/deoren/dev/rsyslog/rsyslog-doc/source/configuration/modules/impstats.rst
/home/deoren/dev/rsyslog/rsyslog-doc/source/configuration/modules/imrelp.rst:343: WARNING: duplicate label statistic-counter, other instance in /home/deoren/dev/rsyslog/rsyslog-doc/source/configuration/modules/imptcp.rst
```

The conflict was not immediately obvious from CI since each PR stood alone and was not rebased against master between each merge (as a result the conflict was not seen).

This will require updating all module docs using the new format to use a unique label for the stats counter section.

I'll submit a PR for those module docs and imuxsock.rst soon.

**Comment by deoren** [comment]
> @deoren: This will require updating all module docs using the new format to use a unique label for the stats counter section.

Turns out that only the module docs already merged were affected.

**Comment by PascalWithopf** [comment]
@deoren here was no label used either

**Comment by deoren** [comment]
@PascalWithopf I think I left this open for feedback on https://github.com/rsyslog/rsyslog-doc/pull/564#issuecomment-365654471.

**Comment by PascalWithopf** [comment]
@deoren I see, sorry, yes this is true, the new style isn't available for this module.

**Comment by deoren** [comment]
@PascalWithopf Thanks for confirming.

**Pull request merged**
