### PR TITLE
imkmsg: rewrite documentation

### PR DESCRIPTION
**Pull request by PascalWithopf**
Module documentation was rewritten in the new style.

### CODE REVIEW

**Comment by deoren** [comment]
Do you know if this module is deprecated or is it just not built by default? When I attempted to load it via `$ModLoad imkmsg` rsyslogd was unable to find the module.

**Comment by rgerhards** [comment]
I just checked, it is in the contrib tree. So I guess @PascalWithopf has just changed the doc format.

**Comment by deoren** [comment]
@rgerhards @PascalWithopf Is it worth noting that the module is not built by default?

**Comment by rgerhards** [comment]
Very, very slippery slope: each distro decides what they build and what the
packaging structure is - quite different btw...


Sent from phone, thus brief.

**Comment by deoren** [comment]
> @rgerhards: Very, very slippery slope: each distro decides what they build and what the
packaging structure is - quite different btw...

Yeah, I can see that; there may be some distros that actually do build it.

**Pull request merged**
