### PR TITLE
imrelp: add doc for parameter oversizeMode

### PR DESCRIPTION
**Pull request by PascalWithopf**
description for parameter maxDataSize was adjusted

### CODE REVIEW

**Comment by deoren** [comment]
related to rsyslog/rsyslog#2656?

Removed 8.35 milestone since the main source project PR isn't set to a specific milestone.

**Comment by rgerhards** [comment]
> related to rsyslog/rsyslog#2656?

I think so - @PascalWithopf can you confirm?

> Removed 8.35 milestone since the main source project PR isn't set to a specific milestone.

err on my part, main issue tracker should have had that milestone. Now it has.

**Comment by PascalWithopf** [comment]
@deoren @rgerhards yes this is related to https://github.com/rsyslog/rsyslog/pull/2656 and https://github.com/rsyslog/rsyslog/pull/2664
One is the pull request for the new parameter oversizeMode and the other is the pull request for the changes in maxDataSize.

**Comment by rgerhards** [comment]
looks like both source PRs are merged

**Pull request merged**
