### PR TITLE
IMHIREDIS::ADDED:: Documentation page for Imhiredis

### PR DESCRIPTION
**Pull request by frikilax**

### CODE REVIEW

**Comment by frikilax** [comment]
Relates to https://github.com/rsyslog/rsyslog/pull/4543

**Comment by rgerhards** [comment]
@frikilax Could you have a look at the (I guess small) doc issues? I am preparing 8.2104 and could merge this into it, if we get it quickly done...

**Comment by frikilax** [comment]
> @frikilax Could you have a look at the (I guess small) doc issues? I am preparing 8.2104 and could merge this into it, if we get it quickly done...

Indeed, fixed !

**Comment by rgerhards** [comment]
@frikilax perfect! Merci!

**Pull request merged**
