### PR TITLE
impstats: rewrite documentation

### PR DESCRIPTION
**Pull request by PascalWithopf**
Module documentation was rewritten in the new style.

### CODE REVIEW

**Comment by deoren** [comment]
@PascalWithopf Re the Caveats / Known Bugs section: 

> This module MUST be loaded right at the top of rsyslog.conf, otherwise stats may not get turned on in all places.

Is that still relevant for the [`advanced`](http://www.rsyslog.com/doc/v8-stable/configuration/conf_formats.html) configuration format?

**Comment by rgerhards** [comment]
I am 95% sure it's right, but for 100% a code review is required.

**Comment by deoren** [comment]
> @rgerhards: I am 95% sure it's right, but for 100% a code review is required.

That the placement at the top of the conf is required or that it is not required?

**Comment by rgerhards** [comment]
I think it needs to go at the top -- IIRC impstats switches a know which is read by other modules at load time. So I would remove that statement only after a code review.

**Comment by deoren** [comment]
> @rgerhards: I think it needs to go at the top -- IIRC impstats switches a know which is read by other modules at load time. So I would remove that statement only after a code review.

ACK.

**Pull request merged**
