### PR TITLE
Sphinx build conf: backout de28b1a changes

### PR DESCRIPTION
**Pull request by deoren**
Commit de28b1a introduced dynamic versioning of content, but failed to take into account the scenario of building the docs from the tarball instead of from a local git repo.

As a quick fix, this commit changes the conf back to an equivalent static version so that the doc sources build as-is from the doc tarball.

I plan to restore dynamic builds in a future PR (likely #493), but this should solve the immediate problem.

refs rsyslog/rsyslog-doc#504, rsyslog/rsyslog-doc#424

### CODE REVIEW

**Comment by deoren** [comment]
@rgerhards Because I'm replacing (at least temporarily) what has proven to be an unstable change to something stable/simple, I'm going to ahead and merge this. 

Please let me know whether this was a problem. I'm working to get PR #493 into a ready state for inclusion soon and I think that will solve some of the aggravation around what I (ironically) intended to be an enhancement to the build process.

I'll rebase, push and remove the blocker label on that PR once the related changeset is ready for review.

**Comment by rgerhards** [comment]
> Please let me know whether this was a problem.

I don't think it was a problem, but I also think it wasn't that urgent. The release tarball is built on release, and the next one is 5 weeks away. At least I would not consider this an emergency to do a re-release. 

@mbiebl do you consider it worth a re-release of the tarball?

**Comment by mbiebl** [comment]
No, as I said, it's not urgent from my side. I already worked around that in the Debian package. 
I just thought I should file that while packaging the latest upstream release.
Please take your time for fixing this properly. There is no need for a new release tarball or urgent changes.

**Comment by rgerhards** [comment]
@mbiebl thanks - your continuous help is much appreciated!

**Comment by deoren** [comment]
@rgerhards @mbiebl Thank you both for your feedback. It sounds like we're good with completely resolving this with the next release then.

**Pull request merged**
