### PR TITLE
fixed queue default values

### PR DESCRIPTION
**Pull request by jvymazal**
attempt to address #365

### CODE REVIEW

**Comment by jvymazal** [comment]
@rgerhards is this viable to merge please?

**Comment by rgerhards** [comment]
yeah, I need to check. and it's still quite a bit until next release ;-)

**Comment by jvymazal** [comment]
@rgerhards , we are now pretty close to a release, could you please look into it? Thanks

**Comment by rgerhards** [comment]
I'll merge, but will change the defaults to the procentual values they actually are.

**Pull request merged**
