### PR TITLE
omkafka: rewrite documentation

### PR DESCRIPTION
**Pull request by PascalWithopf**
Module documentation was rewritten in the new style.

### CODE REVIEW

**Comment by deoren** [comment]
@PascalWithopf Pushed to your branch based on prior permission to do so. Please let me know whether that was intended instead as a one-time thing. 

What do you think of the changes?

**Comment by PascalWithopf** [comment]
@deoren thanks, you can keep pushing your changes, that makes it easier.
I changed the titles of the Example section to match those of the other documentations.

**Comment by deoren** [comment]
> @PascalWithopf: @deoren thanks, you can keep pushing your changes, that makes it easier.

Great, it is working well thus far for me as well.

> @PascalWithopf: I changed the titles of the Example section to match those of the other documentations.

Good idea. I took another look and saw the 'Example 1' section still in place. I pruned it with another push to your branch. Does that work?

If so it looks like this doc is probably ready for merging.

**Comment by PascalWithopf** [comment]
@deoren That is probably a misunderstanding. When I said that I changed the title of the Example section, I added the "Example 1" section.

In this case it looks like it's not necessary, but I when there are multiple examples I think it is useful, especially in a case like this where the example is split into two parts.

**Comment by deoren** [comment]
> @PascalWithopf: @deoren That is probably a misunderstanding. When I said that I changed the title of the Example section, I added the "Example 1" section.
> 
> In this case it looks like it's not necessary, but I when there are multiple examples I think it is useful, especially in a case like this where the example is split into two parts.

Are you saying that the named example sections are not desired, or just for situations where an example is meant to be provided in parts?

**Comment by PascalWithopf** [comment]
@deoren I think the named example sections are a good idea. But in this case I think one title for the whole example is a good idea, because it is related.

**Comment by deoren** [comment]
> @PascalWithopf: @deoren I think the named example sections are a good idea. But in this case I think one title for the whole example is a good idea, because it is related.

Going that route, do you see the fix being to just remove all parent sections so that the single example entry fits below the "Examples" heading?

**Comment by PascalWithopf** [comment]
@deoren I would do it like my commit just now.

**Comment by deoren** [comment]
> @PascalWithopf: @deoren I would do it like seen in my commit just now.

I see what you mean now, group the two items under a common header so it is one logical example. That works.

**Pull request merged**
