### PR TITLE
Add random function coverage

### PR DESCRIPTION
**Pull request by deoren**
Add coverage of `random()` function. Not yet complete, waiting on feedback for related ticket.

closes rsyslog/rsyslog-doc#460

### CODE REVIEW

**Comment by deoren** [comment]
@rgerhards What do you think of the current state of the PR? I backed out a commit where some unrelated whitespace changes were made to make the changes clearer.

**Comment by deoren** [comment]
Rebased/pushed to squash the multiple commits tied to this PR. Unless I have something off with the coverage, this is probably ready to merge.

@rgerhards Any concerns with the coverage as of 4bd9d96af8f347f8aae1b97293d794e444960340?

**Comment by rgerhards** [comment]
small but important comment: I think we should stress that this is not a crypto-grade random number. It actually currently is in most cases, but we do not want to guarantee that. Something along the lines of

"Important note: the random number must not be assume to be of crypto-grade. It may be generated by a very weak random number generator."

Thinking about this, I think we should probably better drop the note on /dev/urandom, as this implies crypto-grade. @deoren what do you think? Am I going overboard? But week PRNG has been too often source of real problems if assumed to be secure....

**Comment by deoren** [comment]
> @rgerhards: small but important comment: I think we should stress that this is not a crypto-grade random number. It actually currently is in most cases, but we do not want to guarantee that. Something along the lines of
> 
> "Important note: the random number must not be assume to be of crypto-grade. It may be generated by a very weak random number generator."
> 
> Thinking about this, I think we should probably better drop the note on /dev/urandom, as this implies crypto-grade. @deoren what do you think? Am I going overboard? But weak PRNG has been too often source of real problems if assumed to be secure....

**Background:**

The change for 8.31.0 specifically mentioned using crypto-grade encryption if it was available and then falling back to PRNG if not. That is where I pulled that statement. 

**Thoughts:**

I believe that mentioning the specifics int he changelog is good, but I see your point regarding giving too much detail in the user doc. The doc is after all intended to reflect the interface, not the implementation. I sometimes forget that when pursuing to cover a feature in detail. I think this is a case where too much detail is not helpful (not "bad", but not really useful either).

I've reworked the wording and added an explicit warning re suitability of the result for crypto use.

**Comment by rgerhards** [comment]
> Background:
> 
> The change for 8.31.0 specifically mentioned using crypto-grade encryption if it was available and then falling back to PRNG if not. That is where I pulled that statement.

haha, looks like my own fail ;-)

> 
> Thoughts:
> 
> I believe that mentioning the specifics int he changelog is good, but I see your point regarding giving too much detail in the user doc. The doc is after all intended to reflect the interface, not the implementation. I sometimes forget that when pursuing to cover a feature in detail. I think this is a case where too much detail is not helpful (not "bad", but not really useful either).

Sometimes it is even bad -- because if we document it, we must support it in the future. For example, a PRNG crypto-grade gurantee would be a real problem on e.g. Solaris, where it is hard to obtain. Here we fall back to just the clib, which is very far from crypto grade. It's no problem, because this is not defined to be crypto grade.

> 
> I've reworked the wording and added an explicit warning re suitability of the result for crypto use.

Looks much better to me :-)

**Comment by deoren** [comment]
> @rgerhards: Sometimes it is even bad -- because if we document it, we must support it in the future. For example, a PRNG crypto-grade gurantee would be a real problem on e.g. Solaris, where it is hard to obtain. Here we fall back to just the clib, which is very far from crypto grade. It's no problem, because this is not defined to be crypto grade.

I see your point. Perhaps there is a compromise somewhere? Providing the information can be useful when a knowledgeable user (perhaps another contributor, a downstream maintainer) runs into an issue, but you still have to make clear (somehow) that the implementation is subject to change. Perhaps a special indicator in the changelog to indicate whether the feature is stable or not?

I dunno, just a thought.

I'll go ahead and merge this.

**Comment by deoren** [comment]
> @deoren: I'll go ahead and merge this.

I meant to say that I'll go ahead and merge this based off of your "looks better" remark.

**Comment by davidelang** [comment]
On Thu, 25 Jan 2018, Deoren Moor wrote:

>> @rgerhards: Sometimes it is even bad -- because if we document it, we must support it in the future. For example, a PRNG crypto-grade gurantee would be a real problem on e.g. Solaris, where it is hard to obtain. Here we fall back to just the clib, which is very far from crypto grade. It's no problem, because this is not defined to be crypto grade.
>
> I see your point. Perhaps there is a compromise somewhere? Providing the information can be useful when a knowledgeable user (perhaps another contributor, a downstream maintainer) runs into an issue, but you still have to make clear (somehow) that the implementation is subject to change. Perhaps a special indicator in the changelog to indicate whether the feature is stable or not?

In this case, there should be no reason for it to ever be crypto-grade (and 
there are those who will argue that /dev/urandom isn't crypto-grade)

so it's best to avoid any inference that this is strong. It's designed for 
statistical sampling/balancing, nothing more.

**Comment by davidelang** [comment]
On Sun, 4 Feb 2018, Deoren Moor wrote:

> @davidelang If I understand you, then even what we have now needs to be modified to remove all references to crypto. Are you suggesting something like this?
>
> ```diff
> -The random number must not be assumed to be crypto-grade. rsyslog will attempt to use a crypto-grade source if available, but it will fall back to a very weak random number generator if a crypto-grade source is not available.
> +The random number must not be assumed to be crypto-grade.
> ```

Yes, the rest of that is too much detail and locks us in.

For example, I could see the random number generator being something that's 
per-thread, and seeded off some something at boot time.

If you think of how early games asked for a random seed at startup, and the same 
seed generated the same sequence of numbers, that sort of very poor randomness 
is sufficient for the purposes of the random function (and for debugging could 
even be seen as a desirable thing)

On Linux /dev/urandom is fast enough and easy enough to use that implementing 
such an internal random number generator is more work, so we'll just use urandom 
:-) but on other systems, and in the future (such as the 4000 clock cycle 
penalty that spectre/meltdown protection can add to a system call), things can 
change

**Comment by deoren** [comment]
@davidelang Fair enough. Thank you for taking the time to go into detail. I'll open a new PR for the changes we discussed here.

**Comment by deoren** [comment]
@davidelang I submitted PR #539 for your review.

**Pull request merged**
