### PR TITLE
Add general author option, epub specific options to build configuration file

### PR DESCRIPTION
**Pull request by deoren**
I wasn't completely sure about some of the values, so let me know if you'd like some changes and I'll work those in.

closes rsyslog/rsyslog-doc#408

### CODE REVIEW

**Comment by rgerhards** [comment]
LGTM! Thx!

**Comment by deoren** [comment]
> @rgerhards: LGTM! Thx!

Welcome. I'll continue looking into sphinx in the hopes of making further improvements over time.

Is there anything further you'd like to have done to this PR before you merge it?

**Comment by rgerhards** [comment]
Just wanted to make sure you see it before I merge :-)

**Comment by deoren** [comment]
@rgerhards thanks

**Pull request merged**
