### PR TITLE
Fix typos in config.enabled parameter name

### PR DESCRIPTION
**Pull request by deoren**
Two cases where "enabled" was used instead of "enable".

### CODE REVIEW

**Comment by deoren** [comment]
Actually, I'm not sure now. The changelog has this to say:

> - config: add ability to disable config parameter ("config.enable")
>   For auto-generated configs, it is useful to have the ability to disable some
>   config constructs even though they may be specified inside the config. This
>   can now be done via the ```config.disable``` parameter, applicable to all
>   script objects. If set to ```on``` or not specified, the construct will be
>   used, if set to any other value, it will be ignored. This can be used
>   together with the backtick functionality to configure enable and disable
>   from either a file or environment variable.
>   closes https://github.com/rsyslog/rsyslog/issues/2431

but checking the tests I find this:

`$ grep -ri "config.enab" .`

```
./grammar/rainerscript.c:       if((valnode = nvlstFindNameCStr(lst, "config.enabled")) != NULL) {
./tests/rscript-config_enable-off-vg.sh:                include(text="stop" config.enabled=`echo $DO_STOP`)
./tests/Makefile.am:    rscript-config_enable-on.sh \
./tests/Makefile.am:    rscript-config_enable-off-vg.sh \
./tests/Makefile.am:    rscript-config_enable-off-vg.sh \
./tests/Makefile.am:    rscript-config_enable-on.sh \
./tests/rscript-config_enable-on.sh:# tests 'config.enabled="on"' -- default value is implicitely check
./tests/rscript-config_enable-on.sh:            include(text="stop" config.enabled=`echo $DO_STOP`)
./ChangeLog:- config: add ability to disable config parameter ("config.enable")
```

Perhaps `config.enabled` is the correct form. If so, the docs and changelog need the other references updated to reflect that.

**Comment by deoren** [comment]
https://github.com/rsyslog/rsyslog/blob/645975c73aadf7b79f6a9289e8f474fa84117c4b/grammar/rainerscript.c#L1214

```c
	/* now config-system parameters (currently a bit hackish, as we
	 * only have one...). -- rgerhards, 2018-01-24
	 */
	if((valnode = nvlstFindNameCStr(lst, "config.enabled")) != NULL) {
		if(es_strbufcmp(valnode->val.d.estr, (unsigned char*) "on", 2)) {
			dbgprintf("config object disabled by configuration\n");
			valnode->bUsed = 1;
			bInError = 1;
		}
	}
```

**Comment by deoren** [comment]
@rgerhards Am I just having an off day today? ;)

## Setup

```
root@ubuntu-1604-virtual-machine:~# echo "sample text" > /tmp/hello.txt
```

## Conf file

`root@ubuntu-1604-virtual-machine:~# cat /etc/rsyslog.conf`

```
module(load="imfile")


input(
  type="imfile" 
  File="/tmp/notyet.txt" 
  Tag="testing-tag"
  config.enabled="off"
)
```

## Validation fail

`root@ubuntu-1604-virtual-machine:~# rsyslogd -N2`

```
rsyslogd: version 8.33.1, config validation run (level 2), master config /etc/rsyslog.conf
rsyslogd: error during parsing file /etc/rsyslog.conf, on or before line 9: parameter 'Tag' not known -- typo in config file? [v8.33.1 try http://www.rsyslog.com/e/2207 ]
rsyslogd: error during parsing file /etc/rsyslog.conf, on or before line 9: parameter 'File' not known -- typo in config file? [v8.33.1 try http://www.rsyslog.com/e/2207 ]
rsyslogd: imfile: no files configured to be monitored - no input will be gathered [v8.33.1 try http://www.rsyslog.com/e/2212 ]
```

## Remove `config.enabled` parameter and retest

```
root@ubuntu-1604-virtual-machine:~# sed -i 's/config.enabled="off"//' /etc/rsyslog.conf
root@ubuntu-1604-virtual-machine:~# rsyslogd -N2
rsyslogd: version 8.33.1, config validation run (level 2), master config /etc/rsyslog.conf
rsyslogd: End of config validation run. Bye.
```

Is this the expected result? If this is a bug I can open a ticket in the source project, I was originally intending to just correct what I thought was a few typos here in the doc project.

**Comment by rgerhards** [comment]
This smells like a bug!

Sent from phone, thus brief.

Am 07.03.2018 19:59 schrieb "Deoren Moor" <notifications@github.com>:

**Comment by deoren** [comment]
@rgerhards I'll open a new issue in the source project then. I'll also plan to provide a debug log when I do.

For the doc updates, it appears that all references to the parameter will need to be updated to reflect `config.enabled` in order to match what is in `grammar/rainerscript.c`.

**Comment by deoren** [comment]
@rgerhards Separate ticket spun off in the source project along with a debug log. 

Re the doc updates for this PR, I think I'm probably done unless you have requests for changes. Review at your convenience.

**Comment by rgerhards** [comment]
I think the doc PR is ready for merge, but we should file an issue with rsyslog (maybe it already exists).

**Comment by rgerhards** [comment]
I mean an issue that when disabled, parameter error messages are issued. config.enabled is correct.

**Comment by deoren** [comment]
> > @rgerhards: I think the doc PR is ready for merge, but we should file an issue with rsyslog (maybe it already exists).
>
> I mean an issue that when disabled, parameter error messages are issued. config.enabled is correct.

I think rsyslog/rsyslog#2520 covers this.

**Comment by deoren** [comment]
- Merging based on https://github.com/rsyslog/rsyslog-doc/pull/614#issuecomment-376079687.  
- rsyslog/rsyslog#2520 covers the errors encountered when disabling a config object via `config.enabled="off"`.

**Pull request merged**
