### PR TITLE
$RepeatedMsgReduction is on by default

### PR DESCRIPTION
**Pull request by gagantrivedi**

### CODE REVIEW

**Comment by rgerhards** [comment]
From what do you conclude the default is "on" -- the code default clearly is "off".

**Comment by gagantrivedi** [comment]
just installed rsyslog on ubuntu 18:04 using apt, please see default generated rsyslog.conf   below
```
#  /etc/rsyslog.conf    Configuration file for rsyslog.
# 
#                       For more information see
#                       /usr/share/doc/rsyslog-doc/html/rsyslog_conf.html
#
#  Default logging rules can be found in /etc/rsyslog.d/50-default.conf


#################
#### MODULES ####
#################

module(load="imuxsock") # provides support for local system logging
#module(load="immark")  # provides --MARK-- message capability

# provides UDP syslog reception
#module(load="imudp")
#input(type="imudp" port="514")

# provides TCP syslog reception
#module(load="imtcp")
#input(type="imtcp" port="514")

# provides kernel logging support and enable non-kernel klog messages
module(load="imklog" permitnonkernelfacility="on")

###########################
#### GLOBAL DIRECTIVES ####
###########################

#
# Use traditional timestamp format.
# To enable high precision timestamps, comment out the following line.
#
$ActionFileDefaultTemplate RSYSLOG_TraditionalFileFormat

# Filter duplicated messages
$RepeatedMsgReduction on

#
# Set the default permissions for all log files.
#
$FileOwner syslog
$FileGroup adm
$FileCreateMode 0640
$DirCreateMode 0755
$Umask 0022
$PrivDropToUser syslog
$PrivDropToGroup syslog

#
# Where to place spool and state files
#
$WorkDirectory /var/spool/rsyslog

#
# Include all config files in /etc/rsyslog.d/
#
$IncludeConfig /etc/rsyslog.d/*.conf
```

**Comment by davidelang** [comment]
That config is set by Ubuntu, it's not the rsyslog default. It explicitly turns 
on message reduction, overriding the default in rsyslog.

David Lang

**Comment by gagantrivedi** [comment]
@davidelang this pull request should be closed then, right?

**Comment by davidelang** [comment]
Yes, and a similar one should be opened against Ubuntu since it's their config 
you are using.

David Lang

**Pull request closed without merging**
