### PR TITLE
omfile: rewrite documentation

### PR DESCRIPTION
**Pull request by PascalWithopf**
Module documentation was rewritten in the new style

### CODE REVIEW

**Comment by deoren** [comment]
Sphinx gets a little confused on this one. When you build the doc and then step one level up to the 'Output Modules' listing you'll see that no only is the omfile entry there, but so are the various subheadings for the doc.

I compared against the imuxsock.rst file to see what the differences were. Here is a quick diff to illustrate what seemed to resolve the issue:

```diff
diff --git a/source/configuration/modules/omfile.rst b/source/configuration/modules/omfile.rst
index 8be884a..ddd6697 100644
--- a/source/configuration/modules/omfile.rst
+++ b/source/configuration/modules/omfile.rst
@@ -1,5 +1,6 @@
+**********************************
 omfile: File Output Module
-==========================
+**********************************

 ===========================  ===========================================================================
 **Module Name:**             **omfile**
```

I've not reviewed the rest of the doc yet, wanted to go ahead and note this before I was interrupted and had to deal with something else.

**Comment by deoren** [comment]
I reviewed the doc further and have some additional suggestions. I'm short on time, so I'm posting a diff here vs providing an inline review (which I understand is probably more helpful).  Sorry about that.

Ref for some of the changes (mappings between 
[`obsolete legacy`](http://www.rsyslog.com/doc/v8-stable/configuration/conf_formats.html) configuration format and [`advanced`](http://www.rsyslog.com/doc/v8-stable/configuration/conf_formats.html) configuration format):

https://github.com/rsyslog/rsyslog/blob/a11719a3bcae526d016a7d71d2d791692d187422/tools/omfile.c#L256

```diff
diff --git a/source/configuration/modules/omfile.rst b/source/configuration/modules/omfile.rst
index 8be884a..158d85e 100644
--- a/source/configuration/modules/omfile.rst
+++ b/source/configuration/modules/omfile.rst
@@ -1,5 +1,6 @@
+**********************************
 omfile: File Output Module
-==========================
+**********************************
 
 ===========================  ===========================================================================
 **Module Name:**             **omfile**
@@ -240,7 +241,7 @@ File
    :widths: auto
    :class: parameter-table
 
-   "string", "none", "no", "none"
+   "string", "none", "no", "``$File``"
 
 This creates a static file output, always writing into the same file.
 If the file already exists, new data is appended to it. Existing
@@ -260,7 +261,7 @@ dynaFile
    :widths: auto
    :class: parameter-table
 
-   "string", "none", "no", "none"
+   "string", "none", "no", "``$DynaFile``"
 
 For each message, the file name is generated based on the given
 template. Then, this file is opened. As with the *file* property,
@@ -435,7 +436,7 @@ ioBufferSize
    :widths: auto
    :class: parameter-table
 
-   "string", "4 KiB", "no", "``$OMFileIOBufferSize``"
+   "size", "4 KiB", "no", "``$OMFileIOBufferSize``"
 
 Size of the buffer used to writing output data. The larger the
 buffer, the potentially better performance is. The default of 4k is
@@ -468,7 +469,7 @@ dirOwnerNum
    :widths: auto
    :class: parameter-table

-   "integer", "system default", "no", "none"
+   "integer", "system default", "no", "``$DirOwnerNum``"

 .. versionadded:: 7.5.8

@@ -504,7 +505,7 @@ dirGroupNum
    :widths: auto
    :class: parameter-table

-   "integer", "system default", "no", "none"
+   "integer", "system default", "no", "``$DirGroupNum``"

 Set the group for directories newly created. Please note that this
 setting does not affect the group of directories already existing.
@@ -538,7 +539,7 @@ fileOwnerNum
    :widths: auto
    :class: parameter-table

-   "integer", "system default", "no", "none"
+   "integer", "system default", "no", "``$FileOwnerNum``"

 .. versionadded:: 7.5.8

@@ -574,7 +575,7 @@ fileGroupNum
    :widths: auto
    :class: parameter-table

-   "integer", "system default", "no", "none"
+   "integer", "system default", "no", "``$FileGroupNum``"

 .. versionadded:: 7.5.8

@@ -690,7 +691,7 @@ the signature feature is turned on.

 Currently there is one signature provider available: ":doc:`ksi_ls12 <sigprov_ksi12>`".

-Previous signature providers ":doc:`gt <sigprov_gt>`" and ":doc:`ksi <sigprov_ksi>`" are depricated.
+Previous signature providers ":doc:`gt <sigprov_gt>`" and ":doc:`ksi <sigprov_ksi>`" are deprecated.


 cry.Provider
```

**Comment by PascalWithopf** [comment]
@deoren I have changed the missing legacy parameters
```
$DirOwnerNum
$DirGroupNum
$FileOwnerNum
$FileGroupNum
```
But I couldn't find anything in the module code suggesting there are parameters like
```
$File
$DynaFile
```

**Comment by rgerhards** [comment]
Sent from phone, thus brief.

Am 05.03.2018 08:40 schrieb "Pascal Withopf" <notifications@github.com>:

@deoren <https://github.com/deoren> I have changed the missing legacy
parameters

$DirOwnerNum
$DirGroupNum
$FileOwnerNum
$FileGroupNum

But I couldn't find anything in the module code suggesting there are
parameters like

$File
$DynaFile


There are no such parameters.

**Comment by deoren** [comment]
> @PascalWithopf: @deoren I have changed the missing legacy parameters
> ```
> $DirOwnerNum
> $DirGroupNum
> $FileOwnerNum
> $FileGroupNum
> ```
> But I couldn't find anything in the module code suggesting there are parameters like
> ```
> $File
> $DynaFile
> ```

> @rgerhards: There are no such parameters.

As @rgerhards indicated, I was wrong about those two. I read over the details too quickly in the source file here:

https://github.com/rsyslog/rsyslog/blob/a11719a3bcae526d016a7d71d2d791692d187422/tools/omfile.c#L277

Just below the comments mapping the new to the old, there are notes indicating that one of the parameters, `file` or `dynafile`, must be present, not that there is (or was) an equivalent directive name for the [`advanced`](http://www.rsyslog.com/doc/v8-stable/configuration/conf_formats.html) configuration format parameters.

**Comment by deoren** [comment]
Thanks @PascalWithopf. Merging now.

**Pull request merged**
