### PR TITLE
Minor tweaks to Container-Features doc

### PR DESCRIPTION
**Pull request by deoren**
- Typo fix
- Use 'kbd' Sphinx directive to highlight the specific keystroke used to exit rsyslog
- Add comments noting points for future expansion

### CODE REVIEW

**Comment by deoren** [comment]
@rgerhards What are your thoughts re TODO comments (those that do not render where the user sees them)? In this case I was looking to add markers for further expansion. Do you feel those remarks belong in the docs or should they only be handled as new issues here?

**Comment by rgerhards** [comment]
I would go for using issues. A strong motivation for this is:

* we can assign milestones
* we can use github project tracking
* **this is more visible/appealing to potential (new) contributors IMHO**

**Comment by deoren** [comment]
> @rgerhards: I would go for using issues. A strong motivation for this is:
> 
> - we can assign milestones
> - we can use github project tracking
> - this is more visible/appealing to potential (new) contributors IMHO

Good points. I'll extract the comments and create separate issues. Once the comments are out I'll squash commits and repush the changes to the associated branch.

**Comment by deoren** [comment]
Updated commit to exclude doc comments.

**Pull request merged**
