### PR TITLE
Update README file: cover building epub, refresh URLs, list assumptions, use virtualenv and local package installs

### PR DESCRIPTION
**Pull request by deoren**
closes rsyslog/rsyslog-doc#405

### CODE REVIEW

**Comment by rgerhards** [comment]
excellent instructions! thx a lot!

**Comment by deoren** [comment]
Welcome. Ironically only after calling it done (and seeing the PR close) did I spot the typos I missed. :P

I will fix & submit via another PR.

**Comment by rgerhards** [comment]
lol, that's the typical "workflow" for me as well (still not caught up on all mail....)

**Comment by deoren** [comment]
Good luck with that. Treading water had to count for something! ;)

**Pull request merged**
