### PR TITLE
Render sysklogd examples as <pre> or the like

### PR DESCRIPTION
**Pull request by Everspace**
I'm not an RST man, but this seemed like an easy fix.

### CODE REVIEW

**Comment by Everspace** [comment]
It was not an easy fix. 

I was following http://docutils.sourceforge.net/docs/ref/rst/restructuredtext.html#literal-blocks

But it currently produces something like 

```
::
# Log info and notice messages to messages file # *.=info;*.=notice;mail.none /var/log/messages
```

In the preview. I'm not quite sure what to do

**Comment by deoren** [comment]
@Everspace Thank you for contributing!

I will have to test the changes to confirm, but I believe the change you made was close, but is missing the newline between the `::` characters and the text you wish to display as code.

In addition to the reST syntax that you mentioned, Sphinx also offers additional options for code formatting:

http://www.sphinx-doc.org/en/stable/markup/code.html

In particular, this is what we're using to convert the module docs to a new format:

https://github.com/rsyslog/rsyslog-doc/pull/608/files#diff-78b9369b56316ecf5f2a309312c1ab81L77

```
.. code-block:: none

   module(load="ommysql")
   action(type="ommysql" server="mysqlserver.example.com" serverport="1234"
          db="syslog_db" uid="user" pwd="pwd")
```

**Comment by deoren** [comment]
@Everspace I just tested and can confirm that adding the newline after the `::` characters resolves the issue for your PR. Ignoring the first change in b82c6c7b709e90b6499bec3d320f3912d6d28d46 (my editor is set to trim all trailing newlines) look at the other changes to see what is needed.

Please let us know if we can assist further and thanks again for contributing. There is a ton of work to do and every little bit helps!

**Comment by Everspace** [comment]
Oh forgive me! Please go ahead an merge. I've found myself more busy unfortunately.

**Comment by deoren** [comment]
> @Everspace: Oh forgive me! Please go ahead an merge. I've found myself more busy unfortunately.

Not a problem, I completely understand the issue with a shortage of time. I've had to curb my own contributions due to other obligations.

I went ahead and committed 74c6daab809254b731a6f828ede23829d25c0ba9 to your branch and will merge in a moment. This commit adds the missing newline that allows your changes to render as intended.

Thank you again for taking the time to contribute fixes to the docs, we appreciate it!

**Pull request merged**
