### PR TITLE
Added two document files; KEYWORDS.csv and METADATA.csv

### PR DESCRIPTION
**Pull request by egberts**
Added two document files; KEYWORDS.csv and METADATA.csv

Was working on railroad diagrams and these files came in handy.

### CODE REVIEW

**Comment by rgerhards** [comment]
I have some concerns adding these files because there is no process that keeps them current. I propose to better add a script that generates them based on the version checked out from git.

**Comment by egberts** [comment]
If you can figure out a way to extract the environment name string that is computed dynamically, then yes we can. But it would require some kind of an Abstract Syntax Tree reconstructor to just to extract the environment name.  

Just mark it as developer internal doc and be done with.

**Comment by rgerhards** [comment]
non maintainable, closing this

**Comment by egberts** [comment]
Might explains why documentation is hard to find, notably with environment variables.

Anyway, for the general peruser, you can find the environment variables (and other things) here:

https://wiki.gentoo.org/wiki/Rsyslog

**Pull request closed without merging**
