### PR TITLE
adding MariaDB to documentation 

### PR DESCRIPTION
**Pull request by robertsilen**
Adding MariaDB to documentation on pages where MySQL is mentioned (see [search for MySQL in docs](https://www.rsyslog.com/doc/search.html?q=mysql&check_keywords=yes&area=default)), with the reasoning "I'm thinking it would be fair considering mariadb is the default in most distros - and it would remove any compatibility doubts too." as per [discussion](https://github.com/rsyslog/rsyslog/issues/5431). 

closes https://github.com/rsyslog/rsyslog/issues/5431

### CODE REVIEW

**Review by rgerhards — APPROVED** [review]

**Comment by rgerhards** [comment]
Thanks for the PR. Can you squash to a single commit? If not, it's OK, then I'll do a manual merge.

**Comment by robertsilen** [comment]
Thank you @rgerhards ! Just curious, when will the changes appear in [the docs](https://www.rsyslog.com/doc/index.html) ?

**Comment by robertsilen** [comment]
Thank you! However, I'm not seeing it yet on the website at e.g. https://www.rsyslog.com/doc/search.html?q=mariadb&check_keywords=yes&area=default# ?

**Comment by rgerhards** [comment]
@robertsilen Thx for the follow-up. As it turned out, the update script had an issue. It now is fixed and the new doc set online.

**Pull request merged**
