### PR TITLE
remove copyright notices from individual pages

### PR DESCRIPTION
**Pull request by jgerhards**
closes https://github.com/rsyslog/rsyslog-doc/issues/455

### CODE REVIEW

**Comment by deoren** [comment]
Awesome, thanks. 

I haven't had time to look into it yet, but the build log notes this issue:

```
/home/travis/build/rsyslog/rsyslog-doc/source/configuration/examples.rst:44:Unknown target name: "adiscon".
```

**Comment by deoren** [comment]
From a test build of the `i455` branch:

```
source/configuration/examples.rst:44: WARNING: Unknown target name: "adiscon".
source/configuration/global/options/rsconf1_debugprintcfsyslinehandlerlist.rst:25: WARNING: Document may not end with a transition.
source/configuration/global/options/rsconf1_debugprintmodulelist.rst:25: WARNING: Document may not end with a transition.
source/configuration/global/options/rsconf1_debugprinttemplatelist.rst:25: WARNING: Document may not end with a transition.
```

**Comment by deoren** [comment]
@jgerhards I've pushed some changes (362acaa007bbf8feb49f75f429ee9cd9b8a34449) to a branch on my fork to illustrate what I think can be done to resolve the issues flagged by CI. 

I'm not familiar enough with GitHub/dev culture to know if it's offensive to merge c0fb71c34ac57f88a872c26f902d54661b2621ab and then merge minor fixes to your changes (362acaa007bbf8feb49f75f429ee9cd9b8a34449) or just commit to my branch and have you cherry pick from that to resolve the CI issues before merging your branch.

**Comment by jgerhards** [comment]
yep, my bad i missed the errors. I think it'd be best to just merge my commit and the directly afterwards your correction

**Comment by deoren** [comment]
@jgerhards fair enough, will do.

**Pull request merged**
