### PR TITLE
build.sh: Fix typos, block accidental commits

### PR DESCRIPTION
**Pull request by deoren**
@rgerhards I found some issues with the build script when attempting to use it as-is for automating regular builds of the branches. I'm not sure that I have all of them squashed, but this fixes at least the most glaring ones. I suspect I'll loop back to this script and make some further tweaks as part of another PR after I have a chance to spend some more time with it.

closes rsyslog/rsyslog-doc#464

### CODE REVIEW

**Comment by deoren** [comment]
@rgerhards Anything about this PR that you'd like me to update?

**Comment by deoren** [comment]
> @rgerhards: TBH I think I used the release_build script in the past (which now seems to be gone). 

I may be to blame for that.

> @rgerhards: But from what I see, this looks good. Let's see what happens when we release 8.32. ;-)

🔥 💣 , me banned from submitting future PRs. :P

**Comment by rgerhards** [comment]
@deoren maybe we should re-add ```release_build.sh``` script (or I keep it personally).  I just tried ```build.sh```and it looks like to does too much for my needs of building just a simple tarball for release ;-)

**Comment by rgerhards** [comment]
oops... indeed we should add a more severe warning. It just merged master into my v8-stable, where it currently does not belong to. Let me see what happened to my other local branches ;-) Maybe time to re-populate from repo... :-)

**Comment by deoren** [comment]
@rgerhards I'll find where the original script last existed and restored it.

> @rgerhards: oops... indeed we should add a more severe warning. It just merged master into my v8-stable, where it currently does not belong

Ouch, sorry about that. I'll also rename the existing script to something more obvious.

**Comment by rgerhards** [comment]
> Ouch, sorry about that. I'll also rename the existing script to something more obvious.

no problem at all. "never run a script you have not fully analyzed" error on my part ;-)

**Comment by rgerhards** [comment]
... and btw: all is restored already :-)

**Comment by rgerhards** [comment]
> @rgerhards I'll find where the original script last existed and restored it.

PR #469 already done -- it was in v8-stable. That branch is set to change on release only (among others, the web interface pulls it to build the latest stable version).

**Comment by deoren** [comment]
@rgerhards Good deal. Sorry again!

**Comment by rgerhards** [comment]
no need to be sorry at all :-D

**Pull request merged**
