### PR TITLE
alternative text for basic-advanced-obsolute format "name" (FOR REVIEW ONLY!)

### PR DESCRIPTION
**Pull request by rgerhards**
This does NOT use sphinx substitutions but instead uses the format
names also in the other text. The idea is to make the names sound
as natural and familar as possible.

### CODE REVIEW

**Comment by deoren** [comment]
@rgerhards You alright with closing this one?

**Comment by rgerhards** [comment]
I wanted to check if we loose some text/idea by closing. If you have time to do so, that would be perfect. If nothing needs to be ammended, close is fine with me.

**Comment by deoren** [comment]
> @rgerhards: I wanted to check if we loose some text/idea by closing. If you have time to do so, that would be perfect. If nothing needs to be ammended, close is fine with me.

I'll give it another pass and try to work more of the content from your PR into the current text. I may add some subsections depending on how much content we end up with.

**Comment by rgerhards** [comment]
I can also do it Monday or Tuesday. I think it is key to be brief.

Sent from phone, thus brief.

Am 17.12.2017 20:02 schrieb "Deoren Moor" <notifications@github.com>:

**Comment by deoren** [comment]
> @rgerhards: I can also do it Monday or Tuesday. I think it is key to be brief.

Understood. This next edit that I share (working on a few different things at once) will likely be an inflated version as I seek to merge existing and new content, but we should be able to trim it back easily enough.

**Comment by deoren** [comment]
@rgerhards How should I layer my changes on top of yours, by a separate branch on my end or by pushing changes to your branch? I didn't think I could, but GitHub is showing me this message as I view this PR:

> Add more commits by pushing to the alttry-fmt-names branch on rgerhards/rsyslog-doc.

For now I'll go ahead and push to a new branch, but I can cherry pick from it to your branch if that is a cleaner way to go about this (proper attribution, etc). That or you could merge from my branch, whatever is easiest. 

This aspect of distributed version control is entirely new to me, I'm used to using a VCS like Subversion so this requires a different way of thinking that I'm not used to just yet. ;)

**Comment by deoren** [comment]
@rgerhards In case you didn't see it, a553a1f30e42a4c02e35b44debf340257cd1e0f8 was my attempt to merge your changes with master. Please let me know what you think. If you want me to push those changes to your branch or close this PR and submit a new one in its place (or some combination?), just let me know.

**Comment by deoren** [comment]
Superseded by PR #447. Closing this PR since these changes were included in that PR.

**Pull request closed without merging**
