### PR TITLE
rainerscript: function documentation split up

### PR DESCRIPTION
**Pull request by PascalWithopf**
The page for rainerscript functions was split up into multiple pages to make it easier to read.

closes https://github.com/rsyslog/rsyslog-doc/issues/634

### CODE REVIEW

**Comment by deoren** [comment]
@PascalWithopf Will try to give this a good review soon (out of time today).

**Comment by PascalWithopf** [comment]
@deoren 
Here is a temporary link to the result for easier review. It will last 7 days after generation and is created from the ubuntu buildbot.
http://ubuntu16.rsyslog.com/doc/doc-2018-03-27-10-56-54-810051f/rainerscript/functions/index.html

**Comment by deoren** [comment]
> @PascalWithopf:  @deoren
>
> Here is a temporary link to the result for easier review. It will last 7 days after generation and is created from the ubuntu buildbot.
> http://ubuntu16.rsyslog.com/doc/doc-2018-03-27-10-56-54-810051f/rainerscript/functions/index.html
> 

Thanks. I've not reviewed the changes exhaustively, but overall I think they're an improvement. 

One thing that I wanted to make sure worked well was one level up from the "Functions" index page; they are:

http://ubuntu16.rsyslog.com/doc/doc-2018-03-27-10-56-54-810051f/rainerscript/index.html

@davidelang What do you think about the changes?

---

@rgerhards When describing the formats from a high level, I understand that we've settled on:

- [`basic`](http://www.rsyslog.com/doc/v8-stable/configuration/conf_formats.html) configuration format

- [`advanced`](http://www.rsyslog.com/doc/v8-stable/configuration/conf_formats.html) configuration format

- [`obsolete legacy`](http://www.rsyslog.com/doc/v8-stable/configuration/conf_formats.html) configuration format

Aside from describing them together, are we still focused on replacing references to "RainerScript" with [`advanced`](http://www.rsyslog.com/doc/v8-stable/configuration/conf_formats.html) configuration format? If describing the "components" of the format, do we drop that name or keep it?

Just curious what the end goal was for that format as a whole.

**Comment by rgerhards** [comment]
> Aside from describing them together, are we still focused on replacing references to "RainerScript" with advanced configuration format? If describing the "components" of the format, do we drop that name or keep it?

let's replace with ```advanced``` -- the root cause for the original name (trademarks) seems to be no longer of concern (99% sure).

**Comment by rgerhards** [comment]
@PascalWithopf looks like I have forced you to do a rebase due to merge order... - please do

**Comment by davidelang** [comment]
please split ltrim/rtrim and num2ipv4/ipv42num into separate lines on the main 
page.

they are related, and should be on the same sub-page, but think of this main 
page as being something that is used by someone who has no idea what these 
functions are, but has a config file that uses them and is trying to figure out 
what they do.

At some point in the future we can have another page (or a second part of this 
page) that groups the functions by what they do in a way that is more helpful 
for someone writing a config who has a rough idea of what they are wanting to do

side note, if cnum() is passed a non-number, we should define what happens. I 
would say that it should return a 0, and log what it was passed as a warning

what does int2hex() do if it's not a positive int?

lookup() refers to lookup_table(), but lookup_table() is not on the list

it is probably a good idea to mention on the re_* functions that they tend to be 
slow and other options may be faster.

on substring, is the first character 0 or 1?

we have a tolower() function, do we have a toupper() function?

**Comment by davidelang** [comment]
On Wed, 28 Mar 2018, Deoren Moor wrote:

> One thing that I wanted to make sure worked well was one level up from the "Functions" index page; they are:
>
> http://ubuntu16.rsyslog.com/doc/doc-2018-03-27-10-56-54-810051f/rainerscript/index.html

a note on this page

"The first full implementation is available since rsyslog v6"

various features have been added since v6, so this is a little misleading (and 
given that all distros are now shipping v7+, it doesn't matter much what 
happened prior to that), there should probably be a note that features are being 
added, so if you are not running the current version, check the docs for the 
version you are running.

> @davidelang What do you think about the changes?

looking good

set/unset/reset should probably be included in the function list.

call_indirect should be included right next to call in control structures.
include() should be included in control structures

look at the various pages 'lookup tables' and below, they look like things that 
belong in a different section than the rest of the page (or should be the 
destinations of some of the other links on the page, for example global() should 
probably link to the page 'global() configuration object' rather than to the 
line on the configuration objexts page that tells you that all the info is on 
the global() configuration object page)

But this is a significant improvement, and should be accepted while we continue 
to improve things.

**Comment by deoren** [comment]
I removed the milestone of 8.34 since it looks like there is still much work to do before this PR is ready (if you consider the full scope of the feedback).

I think we've identified several areas for improvement, both to the specific content intended as the scope for this PR and for other issues with coverage of the [`advanced`](http://www.rsyslog.com/doc/v8-stable/configuration/conf_formats.html) configuration format.

**Proposal**:

- Create separate issues (and PRs) to handle issues noted by @davidelang and myself that are not directly related to the scope of this PR

- Update this PR to address groupings of functions
    - @davidelang mentioned that it would be useful to have an index of all functions separately, but combine them on another page. This sounds like a move away from an automatic index generation to a manual one, but may be the needed workaround to accomplish a full list in one place, but a grouping of the functions in the source files like they are now.
        - e.g., `rs-ipv4convert.rst`  stays like it is, but the index that refers to the page now has two entries for the `num2ipv4()` and `ipv42num()` functions

**Notes**:

- I'm a fan of separate functions per page with a reference to related functions/pages, but that's probably just me. I'm greatly in favor of automation where feasible to help cut out unintentional broken links later.

- If much of the additional feedback is spun off as separate items, it may be that the results can be merged in sooner than later, but I'm guessing still too late for the 8.34 merge window.

**Comment by davidelang** [comment]
On Fri, 30 Mar 2018, Deoren Moor wrote:

> **Proposal**:
>
> - Create separate issues (and PRs) to handle issues noted by @davidelang and myself that are not directly related to the scope of this PR

I agree that this is already a significant improvement and further improvements 
should not block the work already done.

> - Update this PR to address groupings of functions
>    - @davidelang mentioned that it would be useful to have an index of all functions separately, but combine them on another page. This sounds like a move away from an automatic index generation to a manual one, but may be the needed workaround to accomplish a full list in one place, but a grouping of the functions in the source files like they are now.
>        - e.g., `rs-ipv4convert.rst`  stays like it is, but the index that refers to the page now has two entries for the `num2ipv4()` and `ipv42num()` functions
>
> **Notes**:
>
> - I'm a fan of separate functions per page with a reference to related 
> functions/pages, but that's probably just me. I'm greatly in favor of 
> automation where feasible to help cut out unintentional broken links later.

In general I would agree with you, but in this case I think we are going to end 
up with multiple links to the pages, one a simple alphabetical list, and another 
that is grouping them by function.

For the simple list, where we have multiple functions covered in one file 
(ipv4convert for example), we could have symlinks for each function covered in 
the file and the alphabetical list could point at the directory that has some 
real files and some symlinks to be sure everything is included.

> - If much of the additional feedback is spun off as separate items, it may be 
> that the results can be merged in sooner than later, but I'm guessing still 
> too late for the 8.34 merge window.

what we have already is an improvement, perfect is the enemy of better, so I'm 
fine merging it as-is and continuing to improve it.

**Pull request merged**
