### PR TITLE
Various typo fixes and grammar tweaks

### PR DESCRIPTION
**Pull request by deoren**
I'm going ahead and submitting the PR, but I've got some more changes to include on this PR (via the referenced branch). Still getting the hang of Git, GitHub and submitting PRs, so please let me know if I need to go about this differently.

### CODE REVIEW

**Comment by deoren** [comment]
The number of commits ended up being greater than expected. I kept thinking I was through, but then I would go further through my notes and find more entries that I had highlighted. Please let me know if you'd like to have these squashed into a single commit and I'll do so.

**Comment by rgerhards** [comment]
From a purist view, a squash would be great, because all are basically "the same".

**Comment by deoren** [comment]
@rgerhards Squashed and pushed. I searched around and found this guide (https://github.com/servo/servo/wiki/Beginner's-guide-to-rebasing-and-squashing) which walked me through the process.

**Comment by rgerhards** [comment]
@deoren lol, I guess it is the same guide that got me started long ago ;-)

Thanks for all the good work! Much appreciated!

**Comment by deoren** [comment]
> @rgerhards: lol, I guess it is the same guide that got me started long ago ;-)

That's too funny. Small world, eh? :)

> @rgerhards: Thanks for all the good work! Much appreciated!

Welcome! I'm glad I could contribute back in some way. Thank you and your team for what you do and for being approachable to newcomers. :)

**Pull request merged**
