### PR TITLE
Remove unnecessary js and image files

### PR DESCRIPTION
**Pull request by mbiebl**
Those are automatically added by sphinx-build so we don't need to ship
(outdated) copies of those files in the git repository.

Fixes: #85

### CODE REVIEW

**Comment by mbiebl** [comment]
@Ralnoc your feedback would be appreciated since you initially added those files

**Comment by Ralnoc** [comment]
You will want to validate that is actually populates those files when sphinx-build runs. When I had originally put this together, these files were not being filled and had to be manually placed to get it to properly generate the final content.

**Comment by mbiebl** [comment]
@Ralnoc I did test this and noticed no obvious breakage.
With this patch applied:
```
$ ls source/ source/_static/
source/:
community.rst      direct_queue_directq.png   how2help.rst                   _static
compatibility      direct_queue_rsyslog2.png  index.rst                      _templates
concepts           direct_queue_rsyslog.png   installation                   tls_cert_100.jpg
configuration      examples                   licensing.rst                  tls_cert_ca.jpg
conf.py            _ext                       module_workflow.png            tls_cert.jpg
dataflow.png       faq                        proposals                      troubleshooting
development        features.rst               queue_analogy_tv.png           tutorials
direct_queue0.png  free_support.rst           rainerscript                   whitepapers
direct_queue1.png  gssapi.png                 rsyslog_confgraph_complex.png
direct_queue2.png  historical                 rsyslog_confgraph_std.png
direct_queue3.png  history.rst                rsyslog-vers.png

source/_static/:
rsyslog.css

$ sphinx-build --version
Sphinx (sphinx-build) 1.6.5

$ sphinx-build -b html source
[...]

$ ls build/_static/
ajax-loader.gif     comment-close.png  down.png          minus.png     searchtools.js  up-pressed.png
basic.css           comment.png        down-pressed.png  plus.png      sidebar.js      websupport.js
classic.css         default.css        file.png          pygments.css  underscore.js
comment-bright.png  doctools.js        jquery.js         rsyslog.css   up.png

```
The resulting html documents looks fine from what I can see.

**Comment by mbiebl** [comment]
@Ralnoc If there is something specific I should check for, please let me know

**Comment by Ralnoc** [comment]
@mbiebl -

I'd say you should be good, then. 

The best test is to just purge the files like you did, and then run the build again to see the results. As long as the final output meets the requirements you are after, you should be set.

**Pull request merged**
