### PR TITLE
document new global setting 'reportChildProcessExits'

### PR DESCRIPTION
**Pull request by jsiwrk**
Documents rsyslog/rsyslog#3328

### CODE REVIEW

**Comment by jsiwrk** [comment]
@rgerhards : I've mentioned in the doc that this feature will be available since v8.41.0 because the ChangeLog indicates that this is the next version, but now I see that the implementation PR is scheduled for v8.1901. Are you changing the version naming convention? Should I use the latter in the doc?

**Comment by rgerhards** [comment]
> @rgerhards : I've mentioned in the doc that this feature will be available since v8.41.0 because the ChangeLog indicates that this is the next version, but now I see that the implementation PR is scheduled for v8.1901. Are you changing the version naming convention? Should I use the latter in the doc?

yup, see https://rainer.gerhards.net/2014/12/rsyslogs-new-release-cycle-and-versioning-scheme.html

**Comment by rgerhards** [comment]
oops, hold on,  wrong link -- will edit

**Comment by rgerhards** [comment]
correct link https://rainer.gerhards.net/2018/12/rsyslog-version-numbering-change.html

**Comment by jsiwrk** [comment]
Version number corrected. This PR is ready to merge for my part.

**Pull request merged**
