### PR TITLE
im3195: rewrite documentation

### PR DESCRIPTION
**Pull request by PascalWithopf**
Module documentation was rewritten in the new style.

### CODE REVIEW

**Comment by deoren** [comment]
@PascalWithopf Do you think it is worth the effort to convert the [`obsolete legacy`](http://www.rsyslog.com/doc/v8-stable/configuration/conf_formats.html) configuration format example over to the current format? From what I can tell this module isn't built by default and after reviewing the notes it doesn't appear that it will be going forward.

**Comment by deoren** [comment]
I found some issues with the recent changes to imrelp.rst, impstats.rst and imptcp.rst:

```
/home/deoren/dev/rsyslog/rsyslog-doc/source/configuration/modules/impstats.rst:291: WARNING: duplicate label statistic-counter, other instance in /home/deoren/dev/rsyslog/rsyslog-doc/source/configuration/modules/imrelp.rst
/home/deoren/dev/rsyslog/rsyslog-doc/source/configuration/modules/imptcp.rst:540: WARNING: duplicate label statistic-counter, other instance in /home/deoren/dev/rsyslog/rsyslog-doc/source/configuration/modules/impstats.rst
/home/deoren/dev/rsyslog/rsyslog-doc/source/configuration/modules/imrelp.rst:343: WARNING: duplicate label statistic-counter, other instance in /home/deoren/dev/rsyslog/rsyslog-doc/source/configuration/modules/imptcp.rst
```

The conflict was not immediately obvious from CI since each PR stood alone and was not rebased against master between each merge (as a result the conflict was not seen).

This will require updating all module docs using the new format to use a unique label for the stats counter section.

I'll submit a PR for those module docs and imuxsock.rst soon.

**Comment by PascalWithopf** [comment]
@deoren I would leave the example as it is, since the one parameter it has is only available in the legacy format.

**Comment by deoren** [comment]
> @PascalWithopf: @deoren I would leave the example as it is, since the one parameter it has is only available in the legacy format.

Good point, I missed that remark when I glanced over the doc.

**Comment by deoren** [comment]
> @deoren: This will require updating all module docs using the new format to use a unique label for the stats counter section.

Turns out that only the module docs already merged were affected.

**Pull request merged**
